language: java

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'