language: java

jdk:
  - openjdk21

sudo: false
install: true

addons:
  sonarcloud:
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean verify sonar:sonar -Pcoverage