language: java
sudo: required

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=ilyamarvin -Dsonar.projectKey=ilyamarvin_uivprpo -Dsonar.login=a2d9147027bdb17cee77fdbf0d62b345a9514a38

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'