language: java
sudo: required

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean verify sonar:sonar \
    -Dsonar.token=SONAR_TOKEN \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.organization=ilyamarvin_uivprpo \
    -Dsonar.projectKey=ilyamarvin
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'