language: java
sudo: required

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean verify
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'