language: java
sudo: required

jdk:
  - openjdk21

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ilyamarvin_uivprpo

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'