language: java

jdk:
  - openjdk21

sudo: false
install: true

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=ilyamarvin_uivprpo