language: java

jdk:
  - openjdk21

sudo: false

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean verify sonar:sonar -Pcoverage -DskipRedundantTests -Dsonar.projectKey=ilyamarvin_uivprpo

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'