language: java
sudo: required

jdk:
  - openjdk21

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${SONAR_TOKEN}

before_script:
  - sleep 3
  - java --version

script:
  - mvn clean verify
  - mvn jacoco:report
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.verbose=true -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'