language: java

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=ilyamarvin -Dsonar.projectKey=ilyamarvin_uivprpo -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'