language: java
sudo: required

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "ilyamarvin"
    token:
      secure: ${{secrets.SONAR_TOKEN}}

script:
  - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ilyamarvin_uivprpo -Dsonar.organization=ilyamarvin

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'